apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dep1
  name: dep1
  namespace: ns-arg01
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dep1
  type: ClusterIP
status:
  loadBalancer: {}
